version: '3.3'
networks:
  app-net:
    driver: bridge
services:
  postgres:
    image: postgres
    container_name: 'companiesPG'
    environment:
      POSTGRES_USER: ${COMPANIES_PG_USER}
      POSTGRES_PASSWORD: ${COMPANIES_PG_PASS}
      POSTGRES_DB: ${COMPANIES_PG_DBNAME}
    networks:
      - app-net
    ports:
      - 5432:5432
    volumes:
      - ../data:/var/lib/postgresql/data
