version: '3.3'
networks:
  app-net:
    driver: bridge
services:
  postgres:
    image: postgres
    container_name: 'example'
    environment:
      POSTGRES_USER: ${AUTH_PG_USER}
      POSTGRES_PASSWORD: ${AUTH_PG_PASS}
      POSTGRES_DB: ${AUTH_PG_DBNAME}
    networks:
      - app-net
    ports:
      - 5432:5432
    volumes:
      - ../data:/var/lib/postgresql/data
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "send_email:1:3"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
